embed_assets: off
gzip_assets: off

javascripts:
  all:
    - public/javascripts/jquery-1.5.2.min.js
    - public/javascripts/jquery-ui-1.8.12.custom.min.js
    - public/javascripts/jquery.colorbox-min.js
    - public/javascripts/curvycorners.js
    - public/javascripts/application.js
    
stylesheets:
  site:
    - public/stylesheets/global.css
    - public/stylesheets/static.css
    - public/stylesheets/accordion.css
    - public/stylesheets/colorbox.css