# store all availables sizes here
# A - Full Height
# B - Body Height
# C - Upper Bout
# D - Lower Bout

# these will be displayed in this exact order (based on the leftmost numbers)  

1: 
  name: 1/2
  a: 62 1/2
  b: 38
  c: 17 1/4
  d: 22 1/4
  
2: 
  name: 1/2 C
  a: 69
  b: 40 1/2
  c: 19
  d: 24
  
3: 
  name: 3/4 F
  a: 72
  b: 42
  c: 18 3/4
  d: 26 1/2
  
4: 
  name: 3/4
  a: 72
  b: 44 1/2
  c: 20 1/2
  d: 26

5: 
  name: 3/4 L
  a: 73
  b: 45 1/2
  c: 20 1/2
  d: 26 3/4

6: 
  name: 3/4 XL
  a: 73
  b: 46
  c: 20 3/4
  d: 26 5/8

7: 
  name: 7/8 J
  a: 74
  b: 45
  c: 20 1/2
  d: 27 1/2

8: 
  name: 7/8
  a: 76
  b: 46
  c: 22
  d: 27 1/2

9: 
  name: 7/8 B + H
  a: 73
  b: 45
  c: 22
  d: 25 1/2

10: 
  name: 7/8 P
  a: 75
  b: 46
  c: 20 3/4
  d: 29

11: 
  name: 7/8 L
  a: 76 1/2
  b: 47
  c: 22
  d: 28 3/4

12: 
  name: 4/4 S
  a: 75 1/2
  b: 47
  c: 21
  d: 28

13: 
  name: 4/4 P
  a: 78
  b: 50
  c: 21
  d: 28 1/2

14: 
  name: 4/4
  a: 80
  b: 50
  c: 22
  d: 30